<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CounselorSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $counselors = [
        [
            'company_id' => 1,
            'first_name' => 'Andrea',
            'last_name' => 'Sanchez',
            'preferred_name' => 'Andy',
            'birthday' => '1996-03-10',
            'gender' => 'Mujer',
            'phone' => '+54 911 7890-1234',
            'email' => 'andrea.sanchez@example.com',
            'medical_conditions' => '',
            'tshirt_size' => 'M',
            'dietary_restrictions' => 'Vegetariana',
            'contact_name' => 'Miguel Sanchez',
            'email_contact_name' => 'miguel.sanchez@example.com',
            'phone_contact_name' => '+54 911 5678-4321',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 28.0,
            'approval_status' => 'Pendiente',
            'type' => 'Consejero',
            'stake' => 'Buenos Aires Argentina Caseros Stake',
            'ward' => 'Caseros 1st Ward',
            'bishop_email' => 'bishop.caseros1@example.com',
            'bishop_name' => 'Carlos Fernandez',
            'attended' => False,
            'pin' => 'PIN1',
            'checkin' => False,
        ],
        [
            'company_id' => 1,
            'first_name' => 'Lucia',
            'last_name' => 'Fernandez',
            'preferred_name' => 'Lucia F.',
            'birthday' => '1998-07-22',
            'gender' => 'Mujer',
            'phone' => '+54 911 1234-5678',
            'email' => 'lucia.fernandez@example.com',
            'medical_conditions' => 'Ninguno',
            'tshirt_size' => 'S',
            'dietary_restrictions' => 'Vegetariana',
            'contact_name' => 'Maria Fernandez',
            'email_contact_name' => 'maria.fernandez@example.com',
            'phone_contact_name' => '+54 911 8765-4321',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 25.0,
            'approval_status' => 'Pendiente',
            'type' => 'Auxiliar',
            'stake' => 'Buenos Aires Argentina Caseros Stake',
            'ward' => 'Caseros 2nd Ward',
            'bishop_email' => 'bishop.caseros2@example.com',
            'bishop_name' => 'Juan Perez',
            'attended' => False,
            'pin' => 'PIN2',
            'checkin' => False,
        ],
        [
            'company_id' => 2,
            'first_name' => 'Martin',
            'last_name' => 'Gomez',
            'preferred_name' => 'Martin G.',
            'birthday' => '2000-01-15',
            'gender' => 'Hombre',
            'phone' => '+54 911 2345-6789',
            'email' => 'martin.gomez@example.com',
            'medical_conditions' => 'Asma',
            'tshirt_size' => 'L',
            'dietary_restrictions' => '',
            'contact_name' => 'Carlos Gomez',
            'email_contact_name' => 'carlos.gomez@example.com',
            'phone_contact_name' => '+54 911 9876-5432',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 24.0,
            'approval_status' => 'Aprobado',
            'type' => 'Consejero',
            'stake' => 'Buenos Aires Argentina Norte Stake',
            'ward' => 'Norte 1st Ward',
            'bishop_email' => 'bishop.norte1@example.com',
            'bishop_name' => 'Roberto Diaz',
            'attended' => False,
            'pin' => 'PIN1',
            'checkin' => False,
        ],
        [
            'company_id' => 2,
            'first_name' => 'Sofia',
            'last_name' => 'Lopez',
            'preferred_name' => 'Sofi',
            'birthday' => '1997-11-30',
            'gender' => 'Mujer',
            'phone' => '+54 911 3456-7890',
            'email' => 'sofia.lopez@example.com',
            'medical_conditions' => '',
            'tshirt_size' => 'M',
            'dietary_restrictions' => 'Sin gluten',
            'contact_name' => 'Ana Lopez',
            'email_contact_name' => 'ana.lopez@example.com',
            'phone_contact_name' => '+54 911 6543-2109',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 26.0,
            'approval_status' => 'Pendiente',
            'type' => 'Auxiliar',
            'stake' => 'Buenos Aires Argentina Norte Stake',
            'ward' => 'Norte 2nd Ward',
            'bishop_email' => 'bishop.norte2@example.com',
            'bishop_name' => 'Miguel Torres',
            'attended' => False,
            'pin' => 'PIN2',
            'checkin' => False,
        ],
        [
            'company_id' => 3,
            'first_name' => 'Diego',
            'last_name' => 'Martinez',
            'preferred_name' => 'Diego M.',
            'birthday' => '1995-05-05',
            'gender' => 'Hombre',
            'phone' => '+54 911 4567-8901',
            'email' => 'diego.martinez@example.com',
            'medical_conditions' => 'Diabetes',
            'tshirt_size' => 'XL',
            'dietary_restrictions' => '',
            'contact_name' => 'Laura Martinez',
            'email_contact_name' => 'laura.martinez@example.com',
            'phone_contact_name' => '+54 911 3210-9876',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 29.0,
            'approval_status' => 'Aprobado',
            'type' => 'Consejero',
            'stake' => 'Buenos Aires Argentina Oeste Stake',
            'ward' => 'Oeste 1st Ward',
            'bishop_email' => 'bishop.oeste1@example.com',
            'bishop_name' => 'Fernando Ruiz',
            'attended' => False,
            'pin' => 'PIN1',
            'checkin' => False,
        ],
        [
            'company_id' => 3,
            'first_name' => 'Valentina',
            'last_name' => 'Perez',
            'preferred_name' => 'Valen',
            'birthday' => '2002-09-18',
            'gender' => 'Mujer',
            'phone' => '+54 911 5678-9012',
            'email' => 'valentina.perez@example.com',
            'medical_conditions' => '',
            'tshirt_size' => 'M',
            'dietary_restrictions' => 'Vegana',
            'contact_name' => 'Jose Perez',
            'email_contact_name' => 'jose.perez@example.com',
            'phone_contact_name' => '+54 911 2109-8765',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 21.0,
            'approval_status' => 'Pendiente',
            'type' => 'Auxiliar',
            'stake' => 'Buenos Aires Argentina Oeste Stake',
            'ward' => 'Oeste 2nd Ward',
            'bishop_email' => 'bishop.oeste2@example.com',
            'bishop_name' => 'Santiago Lopez',
            'attended' => False,
            'pin' => 'PIN2',
            'checkin' => False,
        ],
    ];
        DB::table('counselors')->insert($counselors);
    }
}
