<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CrosswordWordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $crossword_words = [
            [
                'puzzle_id' => 1,
                'word' => 'PROFETA',
                'normalized_word' => 'PROFETA',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 0,
                'col' => 10,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'ARREPENTIMIENTO',
                'normalized_word' => 'ARREPENTIMIENTO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 1,
                'col' => 2,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'ESCRITURAS',
                'normalized_word' => 'ESCRITURAS',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 1,
                'col' => 7,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'TEMPLO',
                'normalized_word' => 'TEMPLO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 4,
                'col' => 9,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'LIBRO DE MORMON',
                'normalized_word' => 'LIBRODEMORMON',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 4,
                'col' => 13,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'ESPIRITU SANTO',
                'normalized_word' => 'ESPIRITUSANTO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 6,
                'col' => 0,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'GETSEMANI',
                'normalized_word' => 'GETSEMANI',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 6,
                'col' => 7,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'SANTA CENA',
                'normalized_word' => 'SANTACENA',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 7,
                'col' => 0,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'DIOS',
                'normalized_word' => 'DIOS',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 9,
                'col' => 4,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'JESUCRISTO',
                'normalized_word' => 'JESUCRISTO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 9,
                'col' => 9,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'BIBLIA',
                'normalized_word' => 'BIBLIA',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 11,
                'col' => 5,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'MISIONEROS',
                'normalized_word' => 'MISIONEROS',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 11,
                'col' => 7,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'ORACION',
                'normalized_word' => 'ORACION',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 11,
                'col' => 15,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'BAUTISMO',
                'normalized_word' => 'BAUTISMO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 16,
                'col' => 4,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'HIMNOS',
                'normalized_word' => 'HIMNOS',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 18,
                'col' => 5,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'PAZ',
                'normalized_word' => 'PAZ',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 0,
                'col' => 10,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'JOSE SMITH',
                'normalized_word' => 'JOSESMITH',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 0,
                'col' => 16,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'PRIMERA VISION',
                'normalized_word' => 'PRIMERAVISION',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 1,
                'col' => 4,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'TRES',
                'normalized_word' => 'TRES',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 4,
                'col' => 7,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'DOMINGO',
                'normalized_word' => 'DOMINGO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 4,
                'col' => 9,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'MORONI',
                'normalized_word' => 'MORONI',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 5,
                'col' => 13,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'LIBRO DE MORMON',
                'normalized_word' => 'LIBRODEMORMON',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 6,
                'col' => 0,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'TRECE',
                'normalized_word' => 'TRECE',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 8,
                'col' => 1,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'PROFETA',
                'normalized_word' => 'PROFETA',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 8,
                'col' => 11,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'ORAR',
                'normalized_word' => 'ORAR',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 9,
                'col' => 5,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'JESUCRISTO',
                'normalized_word' => 'JESUCRISTO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 10,
                'col' => 0,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'DIOS',
                'normalized_word' => 'DIOS',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 10,
                'col' => 12,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'ARBOLEDA',
                'normalized_word' => 'ARBOLEDA',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 12,
                'col' => 4,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'PLAN DE SALVACION',
                'normalized_word' => 'PLANDESALVACION',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 0,
                'col' => 8,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'RUSSELL M NELSON',
                'normalized_word' => 'RUSSELLMNELSON',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 1,
                'col' => 3,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'SOCIEDAD DE SOCORRO',
                'normalized_word' => 'SOCIEDADDESOCORRO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 4,
                'col' => 0,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'DIA DE REPOSO',
                'normalized_word' => 'DIADEREPOSO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 6,
                'col' => 5,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'PRIMARIA',
                'normalized_word' => 'PRIMARIA',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 6,
                'col' => 11,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'APOSTOLES',
                'normalized_word' => 'APOSTOLES',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 6,
                'col' => 15,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'SACERDOCIO',
                'normalized_word' => 'SACERDOCIO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 7,
                'col' => 1,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'SANTA CENA',
                'normalized_word' => 'SANTACENA',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'vertical',
                'row' => 8,
                'col' => 11,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'CONFERENCIA GENERAL',
                'normalized_word' => 'CONFERENCIAGENERAL',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 13,
                'col' => 0,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'TEMPLO',
                'normalized_word' => 'TEMPLO',
                'clue' => 'Persona que transmite mensajes divinos',
                'direction' => 'horizontal',
                'row' => 18,
                'col' => 0,
            ],
            
        ];

        DB::table('crossword_words')->insert($crossword_words);
    }
}
