<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CrosswordWordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $crossword_words = [
            [
                'puzzle_id' => 1,
                'word' => 'PROFETA',
                'normalized_word' => 'PROFETA',
                'clue' => 'Recibe revelación de Dios',
                'direction' => 'vertical',
                'row' => 0,
                'col' => 10,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'ARREPENTIMIENTO',
                'normalized_word' => 'ARREPENTIMIENTO',
                'clue' => 'Cambio de corazón y acciones',
                'direction' => 'vertical',
                'row' => 1,
                'col' => 2,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'ESCRITURAS',
                'normalized_word' => 'ESCRITURAS',
                'clue' => 'Libros sagrados',
                'direction' => 'horizontal',
                'row' => 1,
                'col' => 7,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'TEMPLO',
                'normalized_word' => 'TEMPLO',
                'clue' => 'Casa sagrada de Dios',
                'direction' => 'horizontal',
                'row' => 4,
                'col' => 9,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'LIBRO DE MORMON',
                'normalized_word' => 'LIBRODEMORMON',
                'clue' => 'Otro testamento de Jesucristo',
                'direction' => 'vertical',
                'row' => 4,
                'col' => 13,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'ESPIRITU SANTO',
                'normalized_word' => 'ESPIRITUSANTO',
                'clue' => 'Consolador y guía espiritual',
                'direction' => 'vertical',
                'row' => 6,
                'col' => 0,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'GETSEMANI',
                'normalized_word' => 'GETSEMANI',
                'clue' => 'Lugar de la agonía de Jesús',
                'direction' => 'vertical',
                'row' => 6,
                'col' => 7,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'SANTA CENA',
                'normalized_word' => 'SANTACENA',
                'clue' => 'Ordinanza con pan y agua',
                'direction' => 'horizontal',
                'row' => 7,
                'col' => 0,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'DIOS',
                'normalized_word' => 'DIOS',
                'clue' => 'Padre Celestial',
                'direction' => 'horizontal',
                'row' => 9,
                'col' => 4,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'JESUCRISTO',
                'normalized_word' => 'JESUCRISTO',
                'clue' => 'Salvador del mundo',
                'direction' => 'vertical',
                'row' => 9,
                'col' => 9,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'BIBLIA',
                'normalized_word' => 'BIBLIA',
                'clue' => 'Libro sagrado cristiano',
                'direction' => 'vertical',
                'row' => 11,
                'col' => 5,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'MISIONEROS',
                'normalized_word' => 'MISIONEROS',
                'clue' => 'Predican el evangelio',
                'direction' => 'horizontal',
                'row' => 11,
                'col' => 7,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'ORACION',
                'normalized_word' => 'ORACION',
                'clue' => 'Comunicación con Dios',
                'direction' => 'vertical',
                'row' => 11,
                'col' => 15,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'BAUTISMO',
                'normalized_word' => 'BAUTISMO',
                'clue' => 'Ordinanza de agua',
                'direction' => 'horizontal',
                'row' => 16,
                'col' => 4,
            ],
            [
                'puzzle_id' => 1,
                'word' => 'HIMNOS',
                'normalized_word' => 'HIMNOS',
                'clue' => 'Canciones de adoración',
                'direction' => 'horizontal',
                'row' => 18,
                'col' => 5,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'PAZ',
                'normalized_word' => 'PAZ',
                'clue' => 'Tranquilidad espiritual',
                'direction' => 'vertical',
                'row' => 0,
                'col' => 10,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'JOSE SMITH',
                'normalized_word' => 'JOSESMITH',
                'clue' => 'Primer profeta moderno',
                'direction' => 'vertical',
                'row' => 0,
                'col' => 16,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'PRIMERA VISION',
                'normalized_word' => 'PRIMERAVISION',
                'clue' => 'Revelación en la arboleda',
                'direction' => 'horizontal',
                'row' => 1,
                'col' => 4,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'TRES',
                'normalized_word' => 'TRES',
                'clue' => 'Número de testigos del Libro de Mormón',
                'direction' => 'vertical',
                'row' => 4,
                'col' => 7,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'DOMINGO',
                'normalized_word' => 'DOMINGO',
                'clue' => 'Día de reposo',
                'direction' => 'vertical',
                'row' => 4,
                'col' => 9,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'MORONI',
                'normalized_word' => 'MORONI',
                'clue' => 'Ángel que entregó las planchas',
                'direction' => 'vertical',
                'row' => 5,
                'col' => 13,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'LIBRO DE MORMON',
                'normalized_word' => 'LIBRODEMORMON',
                'clue' => 'Escritura restaurada',
                'direction' => 'horizontal',
                'row' => 6,
                'col' => 0,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'TRECE',
                'normalized_word' => 'TRECE',
                'clue' => 'Cantidad de Artículos de Fe',
                'direction' => 'vertical',
                'row' => 8,
                'col' => 1,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'PROFETA',
                'normalized_word' => 'PROFETA',
                'clue' => 'Líder espiritual',
                'direction' => 'horizontal',
                'row' => 8,
                'col' => 11,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'ORAR',
                'normalized_word' => 'ORAR',
                'clue' => 'Hablar con Dios',
                'direction' => 'vertical',
                'row' => 9,
                'col' => 5,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'JESUCRISTO',
                'normalized_word' => 'JESUCRISTO',
                'clue' => 'Hijo de Dios',
                'direction' => 'horizontal',
                'row' => 10,
                'col' => 0,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'DIOS',
                'normalized_word' => 'DIOS',
                'clue' => 'Creador del universo',
                'direction' => 'horizontal',
                'row' => 10,
                'col' => 12,
            ],
            [
                'puzzle_id' => 2,
                'word' => 'ARBOLEDA',
                'normalized_word' => 'ARBOLEDA',
                'clue' => 'Lugar de la Primera Visión',
                'direction' => 'horizontal',
                'row' => 12,
                'col' => 4,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'PLAN DE SALVACION',
                'normalized_word' => 'PLANDESALVACION',
                'clue' => 'Propósito de la vida',
                'direction' => 'vertical',
                'row' => 0,
                'col' => 8,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'RUSSELL M NELSON',
                'normalized_word' => 'RUSSELLMNELSON',
                'clue' => 'Presidente actual de la Iglesia',
                'direction' => 'horizontal',
                'row' => 1,
                'col' => 3,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'SOCIEDAD DE SOCORRO',
                'normalized_word' => 'SOCIEDADDESOCORRO',
                'clue' => 'Organización de mujeres',
                'direction' => 'horizontal',
                'row' => 4,
                'col' => 0,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'DIA DE REPOSO',
                'normalized_word' => 'DIADEREPOSO',
                'clue' => 'Día para adorar y descansar',
                'direction' => 'vertical',
                'row' => 6,
                'col' => 5,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'PRIMARIA',
                'normalized_word' => 'PRIMARIA',
                'clue' => 'Organización para niños',
                'direction' => 'horizontal',
                'row' => 6,
                'col' => 11,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'APOSTOLES',
                'normalized_word' => 'APOSTOLES',
                'clue' => 'Doce testigos especiales',
                'direction' => 'vertical',
                'row' => 6,
                'col' => 15,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'SACERDOCIO',
                'normalized_word' => 'SACERDOCIO',
                'clue' => 'Autoridad para servir en la Iglesia',
                'direction' => 'vertical',
                'row' => 7,
                'col' => 1,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'SANTA CENA',
                'normalized_word' => 'SANTACENA',
                'clue' => 'Recordamos a Jesucristo',
                'direction' => 'vertical',
                'row' => 8,
                'col' => 11,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'CONFERENCIA GENERAL',
                'normalized_word' => 'CONFERENCIAGENERAL',
                'clue' => 'Reunión mundial semestral',
                'direction' => 'horizontal',
                'row' => 13,
                'col' => 0,
            ],
            [
                'puzzle_id' => 3,
                'word' => 'TEMPLO',
                'normalized_word' => 'TEMPLO',
                'clue' => 'Lugar de ordenanzas eternas',
                'direction' => 'horizontal',
                'row' => 18,
                'col' => 0,
            ],
            
        ];

        DB::table('crossword_words')->insert($crossword_words);
    }
}
