<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ParticipantSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $participants = [
        [
            'company_id' => 1,
            'first_name' => 'Lucía Fernanda',
            'last_name' => 'Pérez Gómez',
            'preferred_name' => 'Lucía',
            'birthday' => '2008-03-15',
            'gender' => 'Mujer',
            'phone' => '1134567890',
            'email' => 'lucia.perez@example.com',
            'medical_conditions' => 'Ninguno',
            'tshirt_size' => 'M',
            'dietary_restrictions' => 'Vegetariana',
            'contact_name' => 'María Gómez',
            'email_contact_name' => 'maria.gomez@example.com',
            'phone_contact_name' => '1145678901',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 16,
            'approval_status' => 'Aprobado',
            'stake' => 'Buenos Aires Argentina Caseros Stake',
            'ward' => 'Caseros Ward',
            'bishop_email' => 'bishop.caseros@example.com',
            'bishop_name' => 'Juan Pérez',
            'attended' => false,
            'is_member' => true,
            'kit_delivered' => false,
        ],
        [
            'company_id' => 1,
            'first_name' => 'Martín Alejandro',
            'last_name' => 'Rodríguez Díaz',
            'preferred_name' => 'Martín',
            'birthday' => '2007-11-22',
            'gender' => 'Hombre',
            'phone' => '1156789012',
            'email' => 'martin.rodriguez@example.com',
            'medical_conditions' => 'Asma',
            'tshirt_size' => 'L',
            'dietary_restrictions' => 'Sin gluten',
            'contact_name' => 'Ana Díaz',
            'email_contact_name' => 'ana.diaz@example.com',
            'phone_contact_name' => '1167890123',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 17,
            'approval_status' => 'Pendiente',
            'stake' => 'Buenos Aires Argentina Caseros Stake',
            'ward' => 'San Martín Ward',
            'bishop_email' => 'bishop.sanmartin@example.com',
            'bishop_name' => 'Pedro Díaz',
            'attended' => false,
            'is_member' => true,
            'kit_delivered' => false,
        ],
        [
            'company_id' => 1,
            'first_name' => 'Valentina Sofía',
            'last_name' => 'López Ruiz',
            'preferred_name' => 'Valen',
            'birthday' => '2009-08-05',
            'gender' => 'Mujer',
            'phone' => '1178901234',
            'email' => 'valentina.lopez@example.com',
            'medical_conditions' => 'Ninguno',
            'tshirt_size' => 'S',
            'dietary_restrictions' => 'Ninguno',
            'contact_name' => 'Carlos Ruiz',
            'email_contact_name' => 'carlos.ruiz@example.com',
            'phone_contact_name' => '1189012345',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 15,
            'approval_status' => 'Aprobado',
            'stake' => 'Buenos Aires Argentina Caseros Stake',
            'ward' => 'Villa Lynch Ward',
            'bishop_email' => 'bishop.villalynch@example.com',
            'bishop_name' => 'Luis López',
            'attended' => false,
            'is_member' => true,
            'kit_delivered' => false,
        ],
        [
            'company_id' => 2,
            'first_name' => 'Santiago Tomás',
            'last_name' => 'García Fernández',
            'preferred_name' => 'Santi',
            'birthday' => '2008-12-10',
            'gender' => 'Hombre',
            'phone' => '1190123456',
            'email' => 'santiago.garcia@example.com',
            'medical_conditions' => 'Diabetes',
            'tshirt_size' => 'M',
            'dietary_restrictions' => 'Sin azúcar',
            'contact_name' => 'Laura Fernández',
            'email_contact_name' => 'laura.fernandez@example.com',
            'phone_contact_name' => '1101234567',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 15,
            'approval_status' => 'Aprobado',
            'stake' => 'Buenos Aires Argentina Norte Stake',
            'ward' => 'Florida Ward',
            'bishop_email' => 'bishop.florida@example.com',
            'bishop_name' => 'Miguel García',
            'attended' => false,
            'is_member' => true,
            'kit_delivered' => false,
        ],
        [
            'company_id' => 2,
            'first_name' => 'Camila Andrea',
            'last_name' => 'Martínez Castro',
            'preferred_name' => 'Cami',
            'birthday' => '2007-05-30',
            'gender' => 'Mujer',
            'phone' => '1123456789',
            'email' => 'camila.martinez@example.com',
            'medical_conditions' => 'Ninguno',
            'tshirt_size' => 'L',
            'dietary_restrictions' => 'Vegana',
            'contact_name' => 'José Castro',
            'email_contact_name' => 'jose.castro@example.com',
            'phone_contact_name' => '1134567890',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 17,
            'approval_status' => 'Pendiente',
            'stake' => 'Buenos Aires Argentina Norte Stake',
            'ward' => 'Vicente López Ward',
            'bishop_email' => 'bishop.vicentelopez@example.com',
            'bishop_name' => 'Roberto Martínez',
            'attended' => false,
            'is_member' => true,
            'kit_delivered' => false,
        ],
        [
            'company_id' => 2,
            'first_name' => 'Federico Javier',
            'last_name' => 'Ramírez Soto',
            'preferred_name' => 'Fede',
            'birthday' => '2009-09-18',
            'gender' => 'Hombre',
            'phone' => '1145678901',
            'email' => 'federico.ramirez@example.com',
            'medical_conditions' => 'Alergia al maní',
            'tshirt_size' => 'XL',
            'dietary_restrictions' => 'Sin maní',
            'contact_name' => 'Marta Soto',
            'email_contact_name' => 'marta.soto@example.com',
            'phone_contact_name' => '1156789012',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 15,
            'approval_status' => 'Aprobado',
            'stake' => 'Buenos Aires Argentina Norte Stake',
            'ward' => 'Olivos Ward',
            'bishop_email' => 'bishop.olivos@example.com',
            'bishop_name' => 'Sergio Ramírez',
            'attended' => false,
            'is_member' => true,
            'kit_delivered' => false,
        ],
        [
            'company_id' => 3,
            'first_name' => 'Agustina Belén',
            'last_name' => 'Torres Medina',
            'preferred_name' => 'Agus',
            'birthday' => '2008-02-25',
            'gender' => 'Mujer',
            'phone' => '1167890123',
            'email' => 'agustina.torres@example.com',
            'medical_conditions' => 'Ninguno',
            'tshirt_size' => 'M',
            'dietary_restrictions' => 'Ninguno',
            'contact_name' => 'Ricardo Medina',
            'email_contact_name' => 'ricardo.medina@example.com',
            'phone_contact_name' => '1178901234',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 16,
            'approval_status' => 'Aprobado',
            'stake' => 'Buenos Aires Argentina Oeste Stake',
            'ward' => 'Morón Ward',
            'bishop_email' => 'bishop.moron@example.com',
            'bishop_name' => 'Fernando Torres',
            'attended' => false,
            'is_member' => true,
            'kit_delivered' => false,
        ],
        [
            'company_id' => 3,
            'first_name' => 'Nicolás Emanuel',
            'last_name' => 'Gómez Paredes',
            'preferred_name' => 'Nico',
            'birthday' => '2007-07-12',
            'gender' => 'Hombre',
            'phone' => '1189012345',
            'email' => 'nicolas.gomez@example.com',
            'medical_conditions' => 'Ninguno',
            'tshirt_size' => 'L',
            'dietary_restrictions' => 'Vegetariano',
            'contact_name' => 'Patricia Paredes',
            'email_contact_name' => 'patricia.paredes@example.com',
            'phone_contact_name' => '1190123456',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 17,
            'approval_status' => 'Pendiente',
            'stake' => 'Buenos Aires Argentina Oeste Stake',
            'ward' => 'Haedo Ward',
            'bishop_email' => 'bishop.haedo@example.com',
            'bishop_name' => 'Oscar Gómez',
            'attended' => false,
            'is_member' => true,
            'kit_delivered' => false,
        ],
        [
            'company_id' => 3,
            'first_name' => 'Julieta María',
            'last_name' => 'Fernández Ríos',
            'preferred_name' => 'Juli',
            'birthday' => '2009-10-03',
            'gender' => 'Mujer',
            'phone' => '1101234567',
            'email' => 'julieta.fernandez@example.com',
            'medical_conditions' => 'Ninguno',
            'tshirt_size' => 'S',
            'dietary_restrictions' => 'Sin lactosa',
            'contact_name' => 'Esteban Ríos',
            'email_contact_name' => 'esteban.rios@example.com',
            'phone_contact_name' => '1123456789',
            'contact_name_two' => '',
            'email_contact_name_two' => '',
            'phone_contact_name_two' => '',
            'age' => 15,
            'approval_status' => 'Aprobado',
            'stake' => 'Buenos Aires Argentina Oeste Stake',
            'ward' => 'Castelar Ward',
            'bishop_email' => 'bishop.castelar@example.com',
            'bishop_name' => 'Marcos Fernández',
            'attended' => false,
            'is_member' => true,
            'kit_delivered' => false,
        ],
    ];
        DB::table('participants')->insert($participants);
    }
}
