<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WordSearchWordSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $word_search_words = [
            [
                'puzzle_id' => 4,
                'word' => 'COMPASION',
                'start_row' => 2,
                'start_col' => 0,
                'end_row' => 2,
                'end_col' => 8,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'CARIDAD',
                'start_row' => 5,
                'start_col' => 9,
                'end_row' => 5,
                'end_col' => 15,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'PAZ',
                'start_row' => 9,
                'start_col' => 4,
                'end_row' => 9,
                'end_col' => 6,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'PACIENCIA',
                'start_row' => 12,
                'start_col' => 0,
                'end_row' => 12,
                'end_col' => 8,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'CONOCIMIENTO',
                'start_row' => 13,
                'start_col' => 3,
                'end_row' => 13,
                'end_col' => 14,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'PERDON',
                'start_row' => 15,
                'start_col' => 6,
                'end_row' => 15,
                'end_col' => 11,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'VERDAD',
                'start_row' => 16,
                'start_col' => 1,
                'end_row' => 16,
                'end_col' => 6,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'JUSTICIA',
                'start_row' => 17,
                'start_col' => 8,
                'end_row' => 17,
                'end_col' => 15,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'OBEDIENCIA',
                'start_row' => 18,
                'start_col' => 8,
                'end_row' => 18,
                'end_col' => 17,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'MISERICORDIA',
                'start_row' => 19,
                'start_col' => 4,
                'end_row' => 19,
                'end_col' => 15,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'GRATITUD',
                'start_row' => 3,
                'start_col' => 10,
                'end_row' => 10,
                'end_col' => 10,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'TEMPLANZA',
                'start_row' => 9,
                'start_col' => 15,
                'end_row' => 17,
                'end_col' => 15,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'SERVICIO',
                'start_row' => 0,
                'start_col' => 16,
                'end_row' => 7,
                'end_col' => 16,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'HUMILDAD',
                'start_row' => 10,
                'start_col' => 16,
                'end_row' => 17,
                'end_col' => 16,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'SANTIDAD',
                'start_row' => 1,
                'start_col' => 19,
                'end_row' => 8,
                'end_col' => 19,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'FORTALEZA',
                'start_row' => 10,
                'start_col' => 19,
                'end_row' => 18,
                'end_col' => 19,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'SABIDURIA',
                'start_row' => 3,
                'start_col' => 2,
                'end_row' => 11,
                'end_col' => 10,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'ESPERANZA',
                'start_row' => 8,
                'start_col' => 2,
                'end_row' => 0,
                'end_col' => 10,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'PROTECCION',
                'start_row' => 11,
                'start_col' => 1,
                'end_row' => 10,
                'end_col' => 2,
            ],
            [
                'puzzle_id' => 4,
                'word' => 'AMOR',
                'start_row' => 7,
                'start_col' => 15,
                'end_row' => 10,
                'end_col' => 18,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'REVELACION',
                'start_row' => 0,
                'start_col' => 9,
                'end_row' => 0,
                'end_col' => 18,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'SERVICIO',
                'start_row' => 1,
                'start_col' => 0,
                'end_row' => 1,
                'end_col' => 7,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'ETERNIDAD',
                'start_row' => 1,
                'start_col' => 8,
                'end_row' => 1,
                'end_col' => 16,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'PROPOSITO',
                'start_row' => 2,
                'start_col' => 1,
                'end_row' => 2,
                'end_col' => 9,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'TESTIMONIO',
                'start_row' => 11,
                'start_col' => 5,
                'end_row' => 11,
                'end_col' => 14,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'SACERDOCIO',
                'start_row' => 12,
                'start_col' => 5,
                'end_row' => 12,
                'end_col' => 14,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'ARREPENTIMIENTO',
                'start_row' => 15,
                'start_col' => 2,
                'end_row' => 15,
                'end_col' => 16,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'DISCIPULO',
                'start_row' => 19,
                'start_col' => 3,
                'end_row' => 19,
                'end_col' => 11,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'REDENCION',
                'start_row' => 8,
                'start_col' => 0,
                'end_row' => 16,
                'end_col' => 0,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'ORACION',
                'start_row' => 11,
                'start_col' => 1,
                'end_row' => 17,
                'end_col' => 1,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'ESPIRITU',
                'start_row' => 4,
                'start_col' => 3,
                'end_row' => 11,
                'end_col' => 3,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'PAZ',
                'start_row' => 6,
                'start_col' => 10,
                'end_row' => 8,
                'end_col' => 10,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'TEMPLO',
                'start_row' => 3,
                'start_col' => 15,
                'end_row' => 8,
                'end_col' => 15,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'EVANGELIO',
                'start_row' => 6,
                'start_col' => 19,
                'end_row' => 14,
                'end_col' => 19,
            ],
            // Diagonales
            [
                'puzzle_id' => 5,
                'word' => 'FE',
                'start_row' => 4,
                'start_col' => 6,
                'end_row' => 3,
                'end_col' => 7,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'SELLAMIENTO',
                'start_row' => 13,
                'start_col' => 2,
                'end_row' => 3,
                'end_col' => 12,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'BAUTISMO',
                'start_row' => 3,
                'start_col' => 9,
                'end_row' => 10,
                'end_col' => 16,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'PROFETAS',
                'start_row' => 7,
                'start_col' => 11,
                'end_row' => 14,
                'end_col' => 18,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'AMOR',
                'start_row' => 17,
                'start_col' => 14,
                'end_row' => 14,
                'end_col' => 17,
            ],
            [
                'puzzle_id' => 5,
                'word' => 'AMOR',
                'start_row' => 18,
                'start_col' => 7,
                'end_row' => 12,
                'end_col' => 15,
            ],
        ];

        DB::table('word_search_words')->insert($word_search_words);
    }
}
